# Generated by Django 2.0 on 2018-02-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc.Question', verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='reply_radio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc.Option', verbose_name='单选选项'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc.Student', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc.Question', verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc.Questionnaire', verbose_name='问卷'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc.UserInfo', verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc.Grade', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc.Grade', verbose_name='班级'),
        ),
    ]
